#include "plugin_scene.h"

#include <assert.h>
#include <stdio.h>
#include <string.h>

static bool store(uint8_t slot, const char *json) {
    JsonDocument doc;
    assert(deserializeJson(doc, json) == DeserializationError::Ok);
    const char *error = nullptr;
    return plugin_scene_store(slot, doc.as<JsonObject>(), &error);
}

int main(int argc, char **argv) {
    const char *valid = "{\"background\":1580575,\"nodes\":[{\"type\":\"text\","
        "\"x\":50,\"y\":50,\"w\":900,\"h\":150,\"color\":16777215,"
        "\"font\":24,\"text\":\"Berlin 18 C\"}]}";
    assert(store(0, valid));
    const PluginSceneSlot *first = plugin_scene_get(0);
    assert(first && first->ready && first->json);
    const uint32_t revision = first->revision;

    // A rejected frame must retain the last visible scene and its revision.
    const char *bad = "{\"background\":1580575,\"nodes\":[{\"type\":\"text\","
        "\"x\":950,\"y\":50,\"w\":100,\"h\":150,\"color\":16777215,"
        "\"font\":24,\"text\":\"Broken\"}]}";
    assert(!store(0, bad));
    assert(first->revision == revision);
    assert(strstr(first->json, "Berlin 18 C") != nullptr);

    for (uint8_t slot = 1; slot < PLUGIN_SCENE_SLOTS; ++slot) {
        assert(store(slot, valid));
        assert(plugin_scene_get(slot)->ready);
    }
    assert(!store(PLUGIN_SCENE_SLOTS, valid));

    // Optional arguments are actual scene JSON files generated by plugins.
    for (int arg = 1; arg < argc; ++arg) {
        FILE *file = fopen(argv[arg], "rb");
        assert(file);
        char input[4096] = {};
        size_t bytes = fread(input, 1, sizeof(input) - 1, file);
        assert(!ferror(file) && feof(file));
        fclose(file);
        assert(bytes > 0);
        const uint32_t before = plugin_scene_get(0)->revision;
        assert(store(0, input));
        assert(plugin_scene_get(0)->revision == before + 1);
    }

    plugin_scene_clear_all();
    for (uint8_t slot = 0; slot < PLUGIN_SCENE_SLOTS; ++slot) {
        assert(!plugin_scene_get(slot)->ready);
        assert(plugin_scene_get(slot)->json == nullptr);
    }
    puts("plugin scene validation OK");
    return 0;
}
